Fixes of mistakes
Parexy/Multiplayer pull request #90
Opened 2019-06-21 16:56 UTC by sensitivesouris

Fixed a huge number of mistakes, inaccuracies of translation, as well as untranslated strings were translated.

2019-06-21 17:01 UTC, SweptWasTaken approved these changes

2019-07-23 02:14 UTC, mattthewaz requested changes
This Pull Request is full of changes to files other than the language files. It isn't acceptable as-is.

2019-07-23 03:27 UTC, notfood commented
Please split your pull request into particular features so it can be reviewed properly.

2019-11-30 03:58 UTC, notfood commented
Stale

2019-11-30 03:58 UTC, closed without merging